// <auto-generated />
using System;
using DeskFlowAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskFlowAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeskFlowAPI.Models.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nomeCategoria");

                    b.HasKey("Id");

                    b.ToTable("Tb_categoria", (string)null);
                });

            modelBuilder.Entity("DeskFlowAPI.Models.Entidades.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("descricaoDoChamado");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("prioridadeDoChamado");

                    b.Property<string>("SolicitanteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nomeDeQuemSolicitou");

                    b.Property<string>("Solucao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("SolucaoDoChamado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("statusDoChamado");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tituloDoChamado");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tb_chamado", (string)null);
                });

            modelBuilder.Entity("DeskFlowAPI.Models.Entidades.Interacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Autor");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("mensagem");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.ToTable("Tb_interacao", (string)null);
                });

            modelBuilder.Entity("DeskFlowAPI.Models.Entidades.Chamado", b =>
                {
                    b.HasOne("DeskFlowAPI.Models.Entidades.Categoria", "Categoria")
                        .WithMany("Chamados")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("DeskFlowAPI.Models.Entidades.Interacao", b =>
                {
                    b.HasOne("DeskFlowAPI.Models.Entidades.Chamado", "Chamado")
                        .WithMany("Interacoes")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("DeskFlowAPI.Models.Entidades.Categoria", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("DeskFlowAPI.Models.Entidades.Chamado", b =>
                {
                    b.Navigation("Interacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
